# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-02 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20180311_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='long_desc',
            field=models.TextField(default='something long', max_length=2000),
        ),
        migrations.AddField(
            model_name='event',
            name='short_desc',
            field=models.TextField(default='something short', max_length=500),
        ),
    ]
