# Generated by Django 3.0.2 on 2020-02-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20180311_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='long_desc',
            field=models.TextField(default='something short', max_length=2000),
        ),
        migrations.AddField(
            model_name='event',
            name='short_desc',
            field=models.TextField(default='something long', max_length=2000),
        ),
    ]
