# Generated by Django 3.0 on 2020-02-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20180311_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('referal_code', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=50)),
                ('fee', models.CharField(max_length=20)),
            ],
        ),
    ]
