# Generated by Django 3.0 on 2020-02-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_register',
            name='fee',
        ),
    ]
