# Generated by Django 3.0 on 2020-02-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_event_register_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_register',
            name='fee',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
