# Generated by Django 3.0 on 2020-02-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20200202_1958'),
        ('events', '0019_event_register_fee'),
    ]

    operations = [
    ]
