# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-03 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_merge_20200203_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('gen', 'General'), ('cse', 'CSE'), ('ece', 'ECE'), ('eee', 'EEE'), ('it', 'IT'), ('me', 'ME'), ('sta', 'SAPTHA')], default='gen', max_length=3),
        ),
        migrations.AlterField(
            model_name='event_register',
            name='fee',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
