# Generated by Django 3.0 on 2020-02-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20200203_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_register',
            name='fee',
        ),
    ]
