# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-05 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_ambassador_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fee',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='prize',
            field=models.FloatField(),
        ),
    ]
