# Generated by Django 2.0.10 on 2020-02-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20200205_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambassador',
            fields=[
                ('referal_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Ambassador_register',
        ),
    ]
