# Generated by Django 2.0.10 on 2020-02-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20200214_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_register',
            old_name='last_name',
            new_name='college',
        ),
    ]
